### ISSUE TITLE
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'share_api' is using version 1.2.30.

### ISSUE THREAD

**Issue by lizhuoyuan** [albertalrisa/share_api#1]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'share_api' is using version 1.2.30.

**Comment by korenzerah** [comment]
@lizhuoyuan 
updated the kotlin version in the build.gradle of the library locally and it worked. 
changed:
ext.kotlin_version = '1.2.30'
to:
ext.kotlin_version = '1.2.51'
